### ISSUE TITLE
Improve handling of dates

### ISSUE THREAD

**Issue by romanofski** [purebred-mua/purebred-email#16]
With the merge of #15 we've introduced an optic `headerDate` which uses `parseTimeOrError`. The use of this function could end up in an exception which is not handled.
Instead, we would like to avoid using a non-total function and perhaps also `parseTimeM` which uses `IO`.

**Comment by singpolyma** [comment]
`parseTimeM` does not use `IO` but rather any useful failure Monad, including `Maybe` (which would be the normal thing to use here, I expect)
