### ISSUE TITLE
How to use headerFrom to set?

### ISSUE THREAD

**Issue by singpolyma** [purebred-mua/purebred-email#40]
set MIME.headerFrom [x] $ MIME.createTextPlainMessage "hai"

Results in an unmodified message -- that is, the body `hai` is present, but the header is not set.  Using a lower-level style:

    set (MIME.headers . at (s"from")) (Just "b@b.com") $ MIME.createTextPlainMessage "hai"

works, but is obviously less desirable.

**Comment by frasertweedale** [comment]
@singpolyma it appears to be a bug.
