### ISSUE TITLE
export Data.MIME.printContentDisposition

### ISSUE THREAD

**Issue by dylex** [purebred-mua/purebred-email#60]
It would be convenient if this were exported -- there are some use cases where you'd like to render ContentDisposition directly, without going through the HasHeader lens. Thanks!

**Comment by frasertweedale** [comment]
I don't understand.  `printContentDisposition` has type
```
printContentDisposition :: ContentDisposition -> B.ByteString
```
You still need to *get* the `ContentDisposition` out of the message, before you can apply this function to it.

**Comment by frasertweedale** [comment]
OK I think I get it... I found the description confusing but you just want this thing exported ;)

**Comment by dylex** [comment]
Right, yes, sorry, I have a `ContentDisposition` already extracted (and possibly mutated) and just want a rendered string for it, so it'd be great to be able to use `printContentDisposition` directly (for use as an HTTP response header in this case -- building some webmail stuff).

**Comment by frasertweedale** [comment]
Yep, I'll export it.  Will do it this weekend.  Not sure when I'll cut a new release though.

**Comment by dylex** [comment]
No worries, I have a messy workaround for now (mutate message, re-extract header). And great package overall, thanks, just right for what I needed.

**Comment by frasertweedale** [comment]
@dylex that's great.  Would love to know more about what you're using it for :)
