### ISSUE TITLE
Handle multipart/related without type parameter

### ISSUE THREAD

**Issue by tomjaguarpaw** [purebred-mua/purebred-email#68]
Thanks for this useful library!

When purebred-email parses `Content-Type: multipart/related` it [looks for the required parameter `type`](https://github.com/purebred-mua/purebred-email/blob/v0.5/src/Data/MIME.hs#L928-L929). Previously [it didn't do so](https://github.com/purebred-mua/purebred-email/blob/v0.4.3/src/Data/MIME.hs). It seems that the new behaviour is indeed correct, according to [RFC2387](https://datatracker.ietf.org/doc/html/rfc2387).

However, when GMail sends an HTML email with embedded images it sends  a `Content-Type: multipart/related` *without* `type` parameter.  I just sent myself one. It looks like this:

```
Content-Type: multipart/related; boundary="00000000000000ebc705d04cdd14"
```

I can't find anything on search engines for "gmail multipart/related no type parameter" so it seems that no one else is complaining about this RFC-violating behaviour. I don't understand why.

Nonetheless, purebred-email can no longer parse HTML emails with embedded images sent from GMail, or at least I can't work out how to persuade it to. This is rather unfortunate. Could purebred-email be relaxed to tolerate GMail's messages (or is there some workaround that I can use)?

*edit* (@frasertweedale) it seems that several services create non-conforming messages.  Confirmed violators:
- GMail
- Fastmail

**Comment by frasertweedale** [comment]
@tomjaguarpaw thank you for reporting this.

It is most irksome when the world's biggest companies that purportedly hire the best engineers fail to follow straightforward rules in official specifications.

Of course, there must already be a bajillion non-conforming messages already out there, sitting in people's mail archives.  So I guess we have to handle this.

Could you please send a non-conforming message to my personal address (the one used for commits in this project) so that I can observe its full structure?

**Comment by frasertweedale** [comment]
I have reported the issue to both Gmail and Fastmail... though I don't hold much hope of them ever fixing it and, as already discussed, it doesn't help with the non-conformant messages they already generated.

**Comment by tomjaguarpaw** [comment]
May I ask if you have a plan to relax this restriction? I currently have two features I want to implement in an app:

1. Parsing of `Date` headers: requires `Data.IMF`, only available in 0.5
2. Parsing of mail with embedded images from GMail: fails in 0.5 (this issue)

so sadly my app is blocked.

**Comment by frasertweedale** [comment]
@tomjaguarpaw Yes, I will relax the type to make the `type` header optional.  I will try and get to it soon, maybe even this weekend, but I'll commit to end of November at the latest. It is a breaking API change so I'll have to bump the major version.

**Comment by frasertweedale** [comment]
I'm also thinking of proposing an Internet-Draft at IETF to formally relax this restriction and define the semantics for undefined `type` parameter.  Evidently many operators are doing just fine without it, so it makes sense to update the specs to reflect established practice.

**Comment by tomjaguarpaw** [comment]
Thank you!

**Comment by frasertweedale** [comment]
@tomjaguarpaw I've got a branch that resolves this and also #69.  Did you want to check it out and give feedback?

https://github.com/purebred-mua/purebred-email/tree/fix/multipart-related

**Comment by tomjaguarpaw** [comment]
Thanks! I'll check it as soon as I can (probably not before the weekend).

**Comment by tomjaguarpaw** [comment]
I can confirm it works fine for me and parses the example email I could not previously parse.

**Comment by frasertweedale** [comment]
@tomjaguarpaw thank you.  I still have a few changes I want to make before releasing v0.6.  Hope to get it done this weekend.

**Comment by frasertweedale** [comment]
Well, "this weekend" turned out more like 8.5 months later, but watch this space :)

**Comment by frasertweedale** [comment]
https://hackage.haskell.org/package/purebred-email-0.6
