### ISSUE TITLE
Some emails come with invalid charset "ascii"

### ISSUE THREAD

**Issue by tomjaguarpaw** [purebred-mua/purebred-email#69]
The emails from the "[Bits About Money](https://bam.kalzumeus.com/)" newsletter arrive with a charset of `ascii`. This is invalid according to [IANA](https://www.iana.org/assignments/character-sets/character-sets.xhtml): the charset should be `us-ascii`. Nonetheless, I do want to parse it!

My workaround is

```haskell
augmentedCharsets :: CharsetLookup
augmentedCharsets k | k == "ascii" = defaultCharsets "us-ascii"
                    | otherwise = defaultCharsets k
```

I'm not sure what the right solution is. Perhaps `purebred-email` could provide `defaultStrictCharsets` and `defaultLooseCharsets`?

**Comment by frasertweedale** [comment]
`ascii` is not even a registered alias of `us-ascii` (https://www.iana.org/assignments/character-sets/character-sets.xhtml).

@tomjaguarpaw do the mails appear to be generated by a particular program or service (that we could file a ticket against?)

ICU recognises `ascii` as an alias of `us-ascii`, so I'll add it to the default charset lookup in *purebred-email*.  I'll do it and cut a patch-level release in the next week or so.

If you need more charsets, see how we use `Data.Text.ICU.Convert` in *purebred-icu* (which is a plugin for the *purebred* MUA program): https://github.com/purebred-mua/purebred-icu/blob/dc8addbc5e0bb79b58a25cc9351d8da1dbb25c1b/src/Purebred/Plugin/ICU.hs#L69-L76

**Comment by tomjaguarpaw** [comment]
> do the mails appear to be generated by a particular program or service 

Yes, on inspection the headers imply that the mails come from "MailGun".

**Comment by frasertweedale** [comment]
Thanks.  I'll see if I can file an issue and get them to improve
their compatibility.
