### ISSUE TITLE
Add useful MIME optics?

### ISSUE THREAD

**Issue by tomjaguarpaw** [purebred-mua/purebred-email#71]
It seems like these optics would be useful to add. The `parseErrors` one was particularly useful for tracking down the error in https://github.com/purebred-mua/purebred-email/issues/70. I don't see any way of getting hold of the errors otherwise!

If you think they would be useful addition then I can make a PR. Suggestions for the best names would be welcome.

```haskell
bodyOfMIMEMessage :: Lens' MIMEMessage MIME
bodyOfMIMEMessage f = \case
  Message h msg -> Message h <$> f msg

-- MIMEParseError is not exported
parseErrors :: Traversal' MIME _
parseErrors f = \case
  Part b -> pure (Part b)
  Encapsulated msg -> Encapsulated <$> traverseOf bodyOfMIMEMessage (parseErrors f) msg
  Multipart sub b bs -> Multipart sub b <$> traverseOf (traversed . bodyOfMIMEMessage) (parseErrors f) bs
  FailedParse e bs -> flip FailedParse bs <$> f e
```

**Comment by frasertweedale** [comment]
Thanks @tomjaguarpaw for the suggestion.  `bodyOfMIMEMessage` exists (with a more general type) as `Data.IMF.body`.  I'll contemplate the name and whether it's better to have as the big type `MIME`, `MIMEMessage` or perhaps both.  But I'm happy to adopt this idea.

**Comment by tomjaguarpaw** [comment]
> bodyOfMIMEMessage exists (with a more general type) as Data.IMF.body

Ah, I didn't see it because I only looked in `MIME` (although now I've seen it I realise I've used it before).

**Comment by tomjaguarpaw** [comment]
Ah, and I see it *is* exported from `MIME` but it is not in the docs because it is part of a module re-export.

**Comment by frasertweedale** [comment]
Closing as the ask seems to be already satisfied.
