### ISSUE TITLE
Message-ID should be Content-ID?

### ISSUE THREAD

**Issue by tomjaguarpaw** [purebred-mua/purebred-email#75]
This looks suspicious to me, though perhaps I'm misunderstanding something.

https://github.com/purebred-mua/purebred-email/blob/84ab531ab38d6d499e75260b773dcd979f2e1b95/src/Data/MIME.hs#L922-L923

**Comment by frasertweedale** [comment]
oh for sure, that's a typo.  thank you!

**Comment by frasertweedale** [comment]
Fixed in https://github.com/purebred-mua/purebred-email/commit/e1a81522d63b6e8d6a11197e8bdde163b077c537.  Good find and thanks for reporting it!
