### ISSUE TITLE
Inf loop when using `parse (message mime)`

### ISSUE THREAD

**Issue by mpscholten** [purebred-mua/purebred-email#80]
The following expression yields an infinite loop when working with large emails (e.g. 6MB):

```
let result = parse (message mime) message
```

The `purebred-email-parse` tool can parse the email. I've also added the email to the test suite and everything was working fine.

The issue seems to go away when compiling the callsite module with `-O1`. So likely there's some GHC bug getting triggered by this library.

Just wanted to document this issue here. I've put `{-# OPTIONS_GHC -O2 #-}` on top of my call site module to fix this issue.

--

Broken program:

```
{-# OPTIONS_GHC -O0 #-}
module Main where

import Prelude

import qualified Data.IMF
import qualified Data.MIME
import qualified Data.ByteString as B


main = do
    message <- B.readFile "large-email.eml"
    let result = Data.IMF.parse (Data.MIME.message Data.MIME.mime) message

    putStrLn $ (show result)
```

Fixed Program:

```
{-# OPTIONS_GHC -O1 #-}
module Main where

import Prelude

import qualified Data.IMF
import qualified Data.MIME
import qualified Data.ByteString as B


main = do
    message <- B.readFile "large-email.eml"
    let result = Data.IMF.parse (Data.MIME.message Data.MIME.mime) message

    putStrLn $ (show result)
```

Profiling output:

```
	Wed Feb 21 15:21 2024 Time and Allocation Profiling Report  (Final)

	   Main +RTS -p -RTS

	total time  =       11.55 secs   (11551 ticks @ 1000 us, 1 processor)
	total alloc = 6,675,735,280 bytes  (excludes profiling overheads)

COST CENTRE    MODULE                            SRC                                                             %time %alloc

takeTillString Data.IMF.Syntax                   src/Data/IMF/Syntax.hs:(399,1)-(403,39)                          93.0    2.3
fetch          Network.HaskellNet.IMAP           src/Network/HaskellNet/IMAP.hs:(373,1)-(375,61)                   1.7    0.1
eval           Network.HaskellNet.IMAP.Parsers   src/Network/HaskellNet/IMAP/Parsers.hs:(28,1)-(30,51)             1.3   36.4
<|>            Text.Packrat.Parse                src/Text/Packrat/Parse.hs:(85,1)-(92,43)                          1.0   19.3
unfoldr        Control.Lens.Cons.Extras          src/Control/Lens/Cons/Extras.hs:82:1-51                           0.6    4.1
connectSSL     Network.HaskellNet.SSL.Internal   src/Network/HaskellNet/SSL/Internal.hs:(42,1)-(47,98)             0.3   32.6
pappend        Data.Attoparsec.ByteString.Buffer internal/Data/Attoparsec/ByteString/Buffer.hs:(105,1)-(106,78)    0.1    2.3

```

**Comment by frasertweedale** [comment]
Thank you for reporting the issue.

The profiling output is for the program running with `-O0`, `-O1`, `-O2`?  It is not entirely clear.

Could you please provide the problematic email as a reproducer input, with private data sanitised as needed?

**Comment by mpscholten** [comment]
Thanks for the quick reply.

The profiling output is from `-O0`.

I've removed everything from the email that is not needed for reproduction, so only the image from the email signature that is causing the problem is left. [email.eml.zip](https://github.com/purebred-mua/purebred-email/files/14371951/email.eml.zip)

**Comment by frasertweedale** [comment]
Dismal performance is expected with `-O0`.  I know for sure some of the string conversion code in one of the dependencies would be O(n^2) in allocations in the size of the input.  Please compile with optimisations.  Is there a reason you cannot?

**Comment by mpscholten** [comment]
I think we disabled optimizations for the project because something else was broken by optimizer / inliner.

Ok that makes sense 👍 With optimizations the problem is gone.

We could mark this Wontfix then?

**Comment by frasertweedale** [comment]
@mpscholten yes, I will close it.  I appreciate the report.  Cheers!
