### ISSUE TITLE
parse fails on non-ASCII Subject

### ISSUE THREAD

**Issue by joee** [purebred-mua/purebred-email#82]
This parsing fails with the error "Failed reading: satisfy", I assume because the Subject contains non-ASCII characters.

While this might not be email-RFC-compliant, messages like this do make their way through my postfix -> sieve pipeline and arrive in my inbox.  Ideally, I would like a way to process them using a lenient purebred-email parsing option.

```
import Data.Hex
import Data.ByteString.Char8
import Data.Either
import Data.MIME

main = do
  let e = unhex "5375626A6563743A20C2BD20697320612068616C660D0A546F3A203C6578616D706C65406578616D706C652E636F6D3E0D0A0D0A626F64790D0A" :: Either String ByteString
  let b = fromRight "" e
  let e' = parse (message mime) b
--  Data.ByteString.Char8.putStrLn b
  print e'
```

**Comment by frasertweedale** [comment]
There is an RFC (of course) - https://datatracker.ietf.org/doc/html/rfc6532.  Implementing it properly would require significant API breakage.

However, for *just* `Subject` and other unstructured headers, we can get away without any API change.  The header value will be a ByteString that is value UTF-8.  I can get a draft PR for you to review during the weekend.

**Comment by joee** [comment]
FWIW, I have also noticed this problem with the display name of an email address, such as:

```
From: non-ASCII here <example@example.com>
```

I understand that might be more difficult to fix.

**Comment by joee** [comment]
This works great.  In my little test corpus of 1,000 emails it parses 100%, including UTF-8 in both the subject line and the email display-name.

**Comment by frasertweedale** [comment]
Enhancement released in https://hackage.haskell.org/package/purebred-email-0.7
